# kubernetes-fastapi LoadBalancer Service
# Enables the pods in a deployment to be accessible from outside the cluster
apiVersion: v1
kind: Service
metadata:
  name: kube-fastapi-svc
spec:
  selector:
    app: kube-fastapi
  ports:
    - protocol: "TCP"
      port: 8080
      targetPort: 8080
  type: LoadBalancer

---
# kube-fastapi Deployment
# Defines the deployment of the app running in a pod on any worker node
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kube-fastapi
  labels:
    app: kube-fastapi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kube-fastapi
  template:
    metadata:
      labels:
        app: kube-fastapi
    spec:
      containers:
        - name: kube-fastapi
          image: svcxyzz/kubernetes-fastapi:1.0.1
          ports:
            - containerPort: 8080
          imagePullPolicy: Always