apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secret
type: Opaque
data:
  mongo-root-username: dXNlcm5hbWU= #username -> echo -n username | base64
  mongo-root-password: cGFzc3dvcmQ= #password -> echo -n password | base64